version: '3.8'

services:
  grouptool:
    image: chaoyihu/grouptool:master
    container_name: grouptool
    # 根据需求修改外部端口号
    ports:
      - "44532:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=False
    restart: unless-stopped
